spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_ON_EXIT=FALSE
    data-username: sa

liquibase:
  check-change-log-location: true
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  enabled: true
  user: liquibase
